version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    restart: always
    network_mode: "bridge"
    volumes:
      - "./src:/home/app/src"
    command: npm start